
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class LadderGameFactoryTest {
    @Test
    public void testRandomLadderGameCreation() {
        GreaterThanOne numberOfRow = GreaterThanOne.from(5);
        GreaterThanOne numberOfPerson = GreaterThanOne.from(4);
        LadderGame ladderGame = LadderGameFactory.randomLadderGame(numberOfRow, numberOfPerson);

        assertNotNull(ladderGame, "LadderGame 객체가 생성되어야 한다.");
        assertNotNull(ladderGame.getLadderRows(), "Row 배열이 null이 아니어야 한다.");
        assertEquals(numberOfRow.getNumber(), ladderGame.getLadderRows().length, "행(row) 수가 맞아야 한다.");
        assertEquals(numberOfPerson.getNumber(), ladderGame.getLadderRows()[0].getRowState().length, "열(col) 수가 맞아야 한다.");
    }

    @Test
    public void testAutoGeneratedLineCountWithinExpectedRange() {
        GreaterThanOne numberOfRow = GreaterThanOne.from(10);
        GreaterThanOne numberOfPerson = GreaterThanOne.from(5);
        LadderGame ladderGame = LadderGameFactory.randomLadderGame(numberOfRow, numberOfPerson);

        int expectedMaxLines = (int)(numberOfRow.getNumber() * numberOfPerson.getNumber() * 0.3);

        int actualLineCount = 0;
        for (Row row : ladderGame.getLadderRows()) {
            for (int val : row.getRowState()) {
                if (val == 1 || val == -1) actualLineCount++;
            }
        }
        actualLineCount = actualLineCount / 2; // 좌우 선 쌍이므로 2로 나눔

        assertTrue(actualLineCount <= expectedMaxLines, "자동 생성된 가로선 수는 정책 내에서 생성되어야 한다.");
    }

    @Test
    public void testAddLineAndDrawLine() {
        GreaterThanOne numberOfRow = GreaterThanOne.from(5);
        GreaterThanOne numberOfPerson = GreaterThanOne.from(5);
        LadderGame ladderGame = LadderGameFactory.randomLadderGame(numberOfRow, numberOfPerson);

        ladderGame.addLine(0, 0);
        Row firstRow = ladderGame.getLadderRows()[0];
        int[] rowState = firstRow.getRowState();

        assertEquals(1, rowState[0], "첫번째 위치에 가로선 오른쪽 연결선이 그려져야 한다.");
        assertEquals(-1, rowState[1], "두번째 위치에 가로선 왼쪽 연결선이 그려져야 한다.");
    }
}



